### ISSUE TITLE
About training on Bangla Dataset and Finding duration for each character

### ISSUE THREAD

**Issue by rajibul97** [as-ideas/DeepForcedAligner#12]
Hi @cschaefer26,
I have performed training DFA model on Bangla Dataset and predicted duration for sample audio. The duration file (.npy format) ouputs some integer values only for each characters. Then I have used the formula as follows: 
duration of a character = (hop_length* pred_value for particular character)/sample_rate.   Am I right for this case. Kindly help me in this regard.

**Comment by cschaefer26** [comment]
Hi, I understand that you want the durations in seconds? Then its correct. You can look at this example, where the durations are used to cud the wav file into pieces by word durations: https://colab.research.google.com/github/as-ideas/DeepForcedAligner/blob/main/notebooks/train.ipynb#scrollTo=0vlau7hm1nFi

**Comment by rajibul97** [comment]
@cschaefer26 , Thanks for your response. I have got the durations in seconds from your shared link. How have you considered silent characters in texts in DFA model? Are the whitespaces among words also considered as characters? Is it necessary to trim silence from wav file? Also, what would be good size of the dataset for DFA model training?

**Comment by cschaefer26** [comment]
Yeah everything is considered as characters, usually whitespaces and iterpunction are mapped automatically to silent parts. It is definitely useful to trim silences from the wav files as the alignments will be better and converge faster. Generally hard to say how much data you need, but I got usable alignments for datasets as little as 200-500 files (though i cannot say for sure how good the quality was, it was def. usable to train a mediocre forward tacotron model).
